mainsite/urls.py
from django.urls import path, re_path

from . import views

app_name = 'mainsite'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('logout/', views.logout_view, name='logout'),
    path('account/', views.AccountView.as_view(), name='account'),

    path('category/<str:cate_urlname>/', views.category, name='category'),
    re_path(r'^product\/(?:.*)\-(.+)\/$', views.product, name='product'),
    path('register/', views.register, name='register'),
    path('login/', views.login_form, name='login'),
    path('cart/', views.cart_check, name='cart'),
    path('cart/add/<int:prod_id>', views.cart_add, name='cart-add'),
    path('cart/del/<int:cart_id>', views.cart_del, name='cart-del'),
    path('cart/update/<int:prod_id>', views.cart_update, name='cart-update'),
    path('orders/', views.orders, name='customer-orders'),
    path('order/', views.order_process, name='order-process'),
    path('customer/<int:user_id>/orders/<int:order_id>/', views.orders_mod, name='customer-orders-modify'),
    path('customer/settings/', views.customer_settings, kwargs={'selected_setting': 'main'}, name='customer-settings'),
    path('customer/settings/<str:selected_setting>', views.customer_settings, name='customer-setting'),
    path('test/template/', views.test_template, name='test-template'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('mainsite.urls')),
    path('admin/', admin.site.urls),
]

mainsite/views.py
import json
import logging

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.urls import reverse
from django.utils.http import urlencode
from django.utils import timezone
from django.views.generic import View
from django.views.generic.base import TemplateView

from . import models

logger = logging.getLogger("mylogger")


class IndexView(TemplateView):
    template_name = 'store/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = models.Category.objects.get_categories()
        context['products'] = models.Product.objects.all()[:30]

        return context
def logout_view(request):
    if request.user.is_authenticated:
        logout(request)
    return HttpResponseRedirect(reverse('mainsite:index'))

class AccountView(View):
    template_name = 'store/account/index.html'

    @staticmethod
    def validate_password(new_password, confirm_password):
        validated = bool(new_password == confirm_password)
        if validated:
            validated = len(new_password) > 8
        return validated

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        context = {}
        user = request.user
        post = request.POST
        if post.get('formAction') == 'update_details':
            user.first_name = post.get('first_name')
            user.last_name = post.get('last_name')
            user.email = post.get('email')
            user.save()
            context['action'] = {'type':'success', 'info':'Details updated!'}
            return render(request, self.template_name, context)

        if post.get('formAction') == 'change_password':
            if user.check_password(post.get('inputCurrentPassword')):
                if self.validate_password(post.get('inputNewPassword'),
                                          post.get('inputConfirmPassword')):
                    user.set_password(post.get('inputNewPassword'))
                    context['action'] = {'type':'success', 'info':'Password updated!'}
                else:
                    context['action'] = {'type':'danger', 'info':'Different passwords!'}
            else:
                context['action'] = {'type':'danger', 'info':'Error occured!'}

            user.save()

            return render(request, self.template_name, context)

        return HttpResponseRedirect(reverse('mainsite:account'))

class CompleteCategory():
    def __init__(self, parrent_category):
        self.parrent_category = parrent_category
        self.child_categories = []

    def addSubCategory(self, child_categories):
        self.child_categories.append(child_categories)

    def setSubCategoryList(self, child_categories_list):
        self.child_categories = child_categories_list


def get_category_list():
    all_categories = models.Category.objects.all().filter(parentId=0)
    ret_category_list = []

    for category in all_categories:
        complete_category = CompleteCategory(category)
        child_categories = models.Category.objects.all().filter(parentId=category.id)
        # holecategory.sub_categories = sub_categories
        complete_category.setSubCategoryList(child_categories)
        ret_category_list.append(complete_category)

    return ret_category_list

def index(request):
    product_list = models.Product.objects.all()[:30]
    # category_list = Category.objects.all()[:5]
    category_list = get_category_list()
    req_user = request.user
    action = 'none'

    if request.GET.get('action'):
        action = request.GET.get('action')

    context = {
        'product_list': product_list,
        'category_list': category_list,
        'action': action,
        'req_user': req_user,
    }
    return render(request, 'mainsite/index.html', context)

def category(request, cate_urlname):
    category_list = get_category_list()
    req_user = request.user

    try:
        current_category = models.Category.objects.get(urlname=cate_urlname)
    except (KeyError, models.Category.DoesNotExist):
        return HttpResponseRedirect('/')
    product_list = models.Product.objects.filter(product_category=current_category)

    context = {
        'current_category': current_category,
        'product_list': product_list,
        'category_list': category_list,
        'req_user': req_user,
    }

    return render(request, 'mainsite/category.html', context)

def product(request, prod_id):
    category_list = get_category_list()
    req_user = request.user

    try:
        selected_product = models.Product.objects.get(pk=prod_id)
    except (KeyError, models.Product.DoesNotExist):
        return render(
            request,
            'mainsite/product.html',
            {'category_list': category_list, 'req_user': req_user}
            )

    if selected_product.product_stock < 10:
        stock_color = 'badge-danger'
    elif selected_product.product_stock < 20:
        stock_color = 'badge-warning'
    else:
        stock_color = 'badge-success'

    url_product_name = selected_product.product_name.replace(' ', '-')

    if not url_product_name in request.path:
        url_product_name = '%s-%i' % (url_product_name, selected_product.id)
        return HttpResponseRedirect('/product/%s/' % url_product_name)

    context = {
        'product': selected_product,
        'category_list': category_list,
        'stock_color': stock_color,
        'req_user':req_user,
        }
    return render(request, 'mainsite/product.html', context)

def register(request):
    category_list = get_category_list()
    req_user = request.user
    register_error = 'none'
    can_register = True
    if request.user.is_authenticated:
        code = '?%s'% urlencode({'action': 'login_success'})
        url = reverse('mainsite:index')
        return HttpResponseRedirect('%s%s' % (url, ''))
    if request.method == 'POST':
        account_login = request.POST.get('UsernameInput')
        account_password = request.POST.get('PasswordInput')
        account_firstname = request.POST.get('FirstNameInput')
        account_lastname = request.POST.get('LastNameInput')
        account_email = request.POST.get('EmailInput')

        try:
            user = User.objects.create_user(
                username=account_login,
                password=account_password,
                first_name=account_firstname,
                last_name=account_lastname,
                email=account_email,
                )
        except IntegrityError:
            register_error = 'acc_exist'
        else:
            logger.info('%s', (user))
            details = models.CustomerDetails.objects.create_empty(user)
            details.save()

    context = {
        'category_list': category_list,
        'register_error': register_error,
        'can_register': can_register,
        'req_user': req_user,
    }

    return render(request, 'mainsite/registration-form.html', context)

def login_form(request):
    category_list = get_category_list()
    login_error = 'none' #TODO(zakrzu): rename to login_status
    can_login = True

    if request.user.is_authenticated:
        login_error = 'authallow'
        can_login = False

    if request.method == 'POST':
        if request.POST.get('logout') == 'true':
            logout(request)
            can_login = True
        else:
            account_username = request.POST.get('UsernameInput')
            account_password = request.POST.get('PasswordInput')

            user = authenticate(username=account_username, password=account_password)
            if user is not None:
                login(request, user)
                login_error = 'logged'
                can_login = False
            else:
                login_error = 'acc_badnameorpassword'

    req_user = request.user
    context = {
        'category_list': category_list,
        'login_error': login_error,
        'can_login': can_login,
        'req_user': req_user,
    }
    return render(request, 'mainsite/login-form.html', context)

@login_required(login_url='/login/')
def cart_check(request):
    category_list = get_category_list()
    try:
        cart_list = models.Cart.objects.all().filter(cart_user=request.user)
    except (KeyError, models.Cart.DoesNotExist, TypeError):
        cart_list = 'empty'

    if not cart_list:
        cart_list = 'empty'
    req_user = request.user
    context = {
        'category_list': category_list,
        'cart_list': cart_list,
        'req_user': req_user,
    }
    return render(request, 'mainsite/cart.html', context)

@login_required(login_url='/login/')
def cart_add(request, prod_id):
    req_user = request.user
    try:
        get_product = models.Product.objects.get(pk=prod_id)
    except (KeyError, models.Product.DoesNotExist):
        return HttpResponseRedirect(reverse('mainsite:index'))

    new_cart_item = models.Cart(cart_product=get_product, cart_user=req_user)
    new_cart_item.save()
    return HttpResponseRedirect(reverse('mainsite:product', args=(get_product.id,)))

@login_required(login_url='/login/')
def cart_del(request, cart_id):
    response = HttpResponse()
    response.status_code = 200
    try:
        get_cart = models.Cart.objects.get(pk=cart_id)
    except (KeyError, models.Cart.DoesNotExist):
        return HttpResponseRedirect(reverse('mainsite:index'))
    get_cart.delete()
    return HttpResponseRedirect(reverse('mainsite:cart'))

@login_required(login_url='/login/')
def cart_update(request, prod_id):
    response = HttpResponse()
    response.status_code = 404

    if request.method == 'POST':
        body = json.loads(request.body)
        quantity = body.get('cart_quantity')
    else:

mainsite/templates/store/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/3eaad0bea7.js" crossorigin="anonymous"></script>
</head>
<body class="bg-light">
    <nav class="navbar navbar-expand-md navbar-light bg-white border-bottom mb-4">
        <div class="container d-flex justify-content-center">
            <a href="{% url 'mainsite:index' %}" class="navbar-brand">BrandName</a>
            <form action="" class="form-inline w-100">
                <div class="input-group flex-fill">
                    <input type="search" name="" id="" class="form-control">
                    <div class="input-group-prepend">
                        <button type="button" class="btn btn-outline-primary rounded-right">Search</button>
                    </div>
                </div>
            </form>
            <ul class="navbar-nav d-flex flex-fill">
            {% if not user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link text-dark" href="{% url 'mainsite:login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" href="{% url 'mainsite:register' %}">Register</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a type="button" class="p-2 text-dark text-nowrap" href="{% url 'mainsite:cart' %}"><i class="fas fa-shopping-cart"></i> Cart</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-dark" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">{{ user.first_name }} {{ user.last_name }}</a>
                    <div class="dropdown-menu">
                      <a class="dropdown-item" href="{% url 'mainsite:account' %}">Settings</a>
                      <a class="dropdown-item" href="#">Another action</a>
                      <a class="dropdown-item" href="#">Something else here</a>
                      <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="#">Separated link</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a href="{% url 'mainsite:logout' %}" type="button" class="p-2 text-dark text-nowrap">Logout</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    {% if action %}
    <div class="alert alert-{{action.type}}">
        <div class="container">
            {{action.info}}
        </div>
    </div>
    {% endif %}
    {% block content %}{% endblock %}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

mainsite/templates/store/index.html
{% extends 'store/base.html' %}
{% block title %}Index{% endblock %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-lg-3 mb-4">
            <h3>Categories</h3>
            <div class="list-group">
                {% for category in categories %}
                    {% if category.childrens %}
                    <div class="list-group-item list-group-item-action dropdown  dropright">
                        <a href="{% url 'mainsite:category' category.parrent %}" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ category.parrent }}</a>
                        <div class="dropdown-menu">
                            {% for child in category.childrens %}
                            <a href="{% url 'mainsite:category' child.urlname %}" class="dropdown-item">{{ child }}</a>
                            {% endfor %}
                        </div>
                    </div>
                    {% else %}
                    <div class="list-group-item list-group-item-action">
                        <a href="" class="">{{ category.parrent }}</a>
                    </div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
        <div class="col">
            <div class="row">
                {% load static %}
                {% for product in products %}
                <div class="col-md-4">
                    <div class="card mb-4 shadow-sm">
                        <img src="{% static 'mainsite/' %}{{ product.product_image }}" class="card-img-top" alt="{{ product.product_image }}">
                        <div class="card-body">
                          <h5 class="card-title">{{ product }}</h5>
                          <p class="card-text overflow-hidden" style="height: 48px;">{{ product.product_description }}</p>
                          <a href="#" class="btn btn-primary">Go somewhere</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

{% endblock %}