mainsite/urls.py
from django.urls import path, re_path

from . import views

app_name = 'mainsite'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('logout/', views.logout_view, name='logout'),
    path('account/', views.AccountView.as_view(), name='account'),

    path('category/<str:cate_urlname>/', views.category, name='category'),
    re_path(r'^product\/(?:.*)\-(.+)\/$', views.product, name='product'),
    path('register/', views.register, name='register'),
    path('login/', views.login_form, name='login'),
    path('cart/', views.cart_check, name='cart'),
    path('cart/add/<int:prod_id>', views.cart_add, name='cart-add'),
    path('cart/del/<int:cart_id>', views.cart_del, name='cart-del'),
    path('cart/update/<int:prod_id>', views.cart_update, name='cart-update'),
    path('orders/', views.orders, name='customer-orders'),
    path('order/', views.order_process, name='order-process'),
    path('customer/<int:user_id>/orders/<int:order_id>/', views.orders_mod, name='customer-orders-modify'),
    path('customer/settings/', views.customer_settings, kwargs={'selected_setting': 'main'}, name='customer-settings'),
    path('customer/settings/<str:selected_setting>', views.customer_settings, name='customer-setting'),
    path('test/template/', views.test_template, name='test-template'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('mainsite.urls')),
    path('admin/', admin.site.urls),
]

mainsite/views.py
import json
import logging

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.urls import reverse
from django.utils.http import urlencode
from django.utils import timezone
from django.views.generic import View
from django.views.generic.base import TemplateView

from . import models

logger = logging.getLogger("mylogger")


class IndexView(TemplateView):
    template_name = 'store/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = models.Category.objects.get_categories()
        context['products'] = models.Product.objects.all()[:30]

        return context
def logout_view(request):
    if request.user.is_authenticated:
        logout(request)
    return HttpResponseRedirect(reverse('mainsite:index'))

class AccountView(View):
    template_name = 'store/account/index.html'

    @staticmethod
    def validate_password(new_password, confirm_password):
        validated = bool(new_password == confirm_password)
        if validated:
            validated = len(new_password) > 8
        return validated

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        context = {}
        user = request.user
        post = request.POST
        if post.get('formAction') == 'update_details':
            user.first_name = post.get('first_name')
            user.last_name = post.get('last_name')
            user.email = post.get('email')
            user.save()
            context['action'] = {'type':'success', 'info':'Details updated!'}
            return render(request, self.template_name, context)

        if post.get('formAction') == 'change_password':
            if user.check_password(post.get('inputCurrentPassword')):
                if self.validate_password(post.get('inputNewPassword'),
                                          post.get('inputConfirmPassword')):
                    user.set_password(post.get('inputNewPassword'))
                    context['action'] = {'type':'success', 'info':'Password updated!'}
                else:
                    context['action'] = {'type':'danger', 'info':'Different passwords!'}
            else:
                context['action'] = {'type':'danger', 'info':'Error occured!'}

            user.save()

            return render(request, self.template_name, context)

        return HttpResponseRedirect(reverse('mainsite:account'))

class CompleteCategory():
    def __init__(self, parrent_category):
        self.parrent_category = parrent_category
        self.child_categories = []

    def addSubCategory(self, child_categories):
        self.child_categories.append(child_categories)

    def setSubCategoryList(self, child_categories_list):
        self.child_categories = child_categories_list


def get_category_list():
    all_categories = models.Category.objects.all().filter(parentId=0)
    ret_category_list = []

    for category in all_categories:
        complete_category = CompleteCategory(category)
        child_categories = models.Category.objects.all().filter(parentId=category.id)
        # holecategory.sub_categories = sub_categories
        complete_category.setSubCategoryList(child_categories)
        ret_category_list.append(complete_category)

    return ret_category_list

def index(request):
    product_list = models.Product.objects.all()[:30]
    # category_list = Category.objects.all()[:5]
    category_list = get_category_list()
    req_user = request.user
    action = 'none'

    if request.GET.get('action'):
        action = request.GET.get('action')

    context = {
        'product_list': product_list,
        'category_list': category_list,
        'action': action,
        'req_user': req_user,
    }
    return render(request, 'mainsite/index.html', context)

def category(request, cate_urlname):
    category_list = get_category_list()
    req_user = request.user

    try:
        current_category = models.Category.objects.get(urlname=cate_urlname)
    except (KeyError, models.Category.DoesNotExist):
        return HttpResponseRedirect('/')
    product_list = models.Product.objects.filter(product_category=current_category)

    context = {
        'current_category': current_category,
        'product_list': product_list,
        'category_list': category_list,
        'req_user': req_user,
    }

    return render(request, 'mainsite/category.html', context)

def product(request, prod_id):
    category_list = get_category_list()
    req_user = request.user

    try:
        selected_product = models.Product.objects.get(pk=prod_id)
    except (KeyError, models.Product.DoesNotExist):
        return render(
            request,
            'mainsite/product.html',
            {'category_list': category_list, 'req_user': req_user}
            )

    if selected_product.product_stock < 10:
        stock_color = 'badge-danger'
    elif selected_product.product_stock < 20:
        stock_color = 'badge-warning'
    else:
        stock_color = 'badge-success'

    url_product_name = selected_product.product_name.replace(' ', '-')

    if not url_product_name in request.path:
        url_product_name = '%s-%i' % (url_product_name, selected_product.id)
        return HttpResponseRedirect('/product/%s/' % url_product_name)

    context = {
        'product': selected_product,
        'category_list': category_list,
        'stock_color': stock_color,
        'req_user':req_user,
        }
    return render(request, 'mainsite/product.html', context)

def register(request):
    category_list = get_category_list()
    req_user = request.user
    register_error = 'none'
    can_register = True
    if request.user.is_authenticated:
        code = '?%s'% urlencode({'action': 'login_success'})
        url = reverse('mainsite:index')
        return HttpResponseRedirect('%s%s' % (url, ''))
    if request.method == 'POST':
        account_login = request.POST.get('UsernameInput')
        account_password = request.POST.get('PasswordInput')
        account_firstname = request.POST.get('FirstNameInput')
        account_lastname = request.POST.get('LastNameInput')
        account_email = request.POST.get('EmailInput')

        try:
            user = User.objects.create_user(
                username=account_login,
                password=account_password,
                first_name=account_firstname,
                last_name=account_lastname,
                email=account_email,
                )
        except IntegrityError:
            register_error = 'acc_exist'
        else:
            logger.info('%s', (user))
            details = models.CustomerDetails.objects.create_empty(user)
            details.save()

    context = {
        'category_list': category_list,
        'register_error': register_error,
        'can_register': can_register,
        'req_user': req_user,
    }

    return render(request, 'mainsite/registration-form.html', context)

def login_form(request):
    category_list = get_category_list()
    login_error = 'none' #TODO(zakrzu): rename to login_status
    can_login = True

    if request.user.is_authenticated:
        login_error = 'authallow'
        can_login = False

    if request.method == 'POST':
        if request.POST.get('logout') == 'true':
            logout(request)
            can_login = True
        else:
            account_username = request.POST.get('UsernameInput')
            account_password = request.POST.get('PasswordInput')

            user = authenticate(username=account_username, password=account_password)
            if user is not None:
                login(request, user)
                login_error = 'logged'
                can_login = False
            else:
                login_error = 'acc_badnameorpassword'

    req_user = request.user
    context = {
        'category_list': category_list,
        'login_error': login_error,
        'can_login': can_login,
        'req_user': req_user,
    }
    return render(request, 'mainsite/login-form.html', context)

@login_required(login_url='/login/')
def cart_check(request):
    category_list = get_category_list()
    try:
        cart_list = models.Cart.objects.all().filter(cart_user=request.user)
    except (KeyError, models.Cart.DoesNotExist, TypeError):
        cart_list = 'empty'

    if not cart_list:
        cart_list = 'empty'
    req_user = request.user
    context = {
        'category_list': category_list,
        'cart_list': cart_list,
        'req_user': req_user,
    }
    return render(request, 'mainsite/cart.html', context)

@login_required(login_url='/login/')
def cart_add(request, prod_id):
    req_user = request.user
    try:
        get_product = models.Product.objects.get(pk=prod_id)
    except (KeyError, models.Product.DoesNotExist):
        return HttpResponseRedirect(reverse('mainsite:index'))

    new_cart_item = models.Cart(cart_product=get_product, cart_user=req_user)
    new_cart_item.save()
    return HttpResponseRedirect(reverse('mainsite:product', args=(get_product.id,)))

@login_required(login_url='/login/')
def cart_del(request, cart_id):
    response = HttpResponse()
    response.status_code = 200
    try:
        get_cart = models.Cart.objects.get(pk=cart_id)
    except (KeyError, models.Cart.DoesNotExist):
        return HttpResponseRedirect(reverse('mainsite:index'))
    get_cart.delete()
    return HttpResponseRedirect(reverse('mainsite:cart'))

@login_required(login_url='/login/')
def cart_update(request, prod_id):
    response = HttpResponse()
    response.status_code = 404

    if request.method == 'POST':
        body = json.loads(request.body)
        quantity = body.get('cart_quantity')
    else:

mainsite/templates/mainsite/base_template.html
<!DOCTYPE html>
<html lang="en" class="h-100">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href="{% static 'mainsite/css/all.css' %}"> -->
    <script src="https://kit.fontawesome.com/3eaad0bea7.js" crossorigin="anonymous"></script>
    <title>{% block title %}{% endblock %}</title>
    <style>

    </style>
</head>
<body class="d-flex flex-column h-100 bg-light">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark shadow-sm">
        <a class="navbar-brand" href="{% url 'mainsite:index' %}">Shop</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'mainsite:index' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                {% if category_list %}
                    {% for category in category_list %}
                        {% if category.child_categories %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="{% url 'mainsite:category' category.parrent_category.urlname %}" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {{ category.parrent_category.name }}
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                {% for subcategory in category.child_categories %}
                                {% if current_category == subcategory %}
                                <a class="dropdown-item active" href="{% url 'mainsite:category' subcategory.urlname %}">{{ subcategory.name }}</a>
                                {% else %}
                                <a class="dropdown-item" href="{% url 'mainsite:category' subcategory.urlname %}">{{ subcategory.name }}</a>
                                {% endif %}
                                {% endfor %}
                            </div>
                        </li>
                        {% else %}
                        {% if current_category == category.parrent_category %}
                        <li class="nav-item active"><a href="{% url 'mainsite:category' category.parrent_category.urlname %}" class="nav-link">{{ category.parrent_category.name }}</a></li>
                        {% else %}
                        <li class="nav-item"><a href="{% url 'mainsite:category' category.parrent_category.urlname %}" class="nav-link">{{ category.parrent_category.name }}</a></li>
                        {% endif %}
                        {% endif %}
                    {% endfor %}
                {% endif %}
                <!-- <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Dropdown link
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li> -->
            </ul>
        <ul class="navbar-nav my-2 my-lg-0">
            {% if req_user.is_authenticated %}
            <li class="nav-item">
                <a class="btn btn-outline-light mr-sm-2" href="{% url 'mainsite:cart' %}"><i class="fas fa-shopping-cart"></i> Cart</a>
            </li>
            <li class="nav-item">
                <span class="navbar-text text-light mr-sm-2">Welcome  
                    <div class="dropdown d-inline-flex">
                        <a href="#" role="button" class="dropdown-toggle" id="username-menu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <b> {% if user.first_name == '' %}{{ user.username }}{% else %}{{ user.first_name }} {{ user.last_name }}{% endif %}</b>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="username-menu">
                            <a href="{% url 'mainsite:customer-orders' %}" class="dropdown-item text-dark">
                                Orders
                            </a>
                            <a href="{% url 'mainsite:customer-settings' %}" class="dropdown-item text-dark">
                                Settings
                            </a>
                        </div> 
                    </div>!</span>
            </li>
            <li class="nav-item">
                <form action="/login/" method="post">
                    {% csrf_token %}
                    <input type="text" name="logout" hidden="true" id="" value="true">
                    <button type="submit" class="btn btn-outline-warning my-2 my-sm-0">Logout</button>
                </form>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="btn btn-primary mr-sm-2" href="{% url 'mainsite:login' %}" role="button">Login</a>
            </li>
            <li class="nav-item">
                <a class="btn btn-secondary" href="{% url 'mainsite:register' %}" role="button">Register</a>
            </li>
            {% endif %}
        </ul>
    </div>
    </nav>
    <main role="main">
          


            <div class="container-fluid" style="margin-top: 25px">
                {% block content %}{% endblock %}
            </div>


    </main>
    <footer class="footer mt-auto py-3"><div class="container"><span class="text-muted">Copyright to Michał Zakrzewski &copy; 2020</span></div></footer>
    {% block script-bottom %}{% endblock %}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

mainsite/templates/mainsite/cart.html
{% extends 'mainsite/base_template.html' %}
{% block title %}Cart{% endblock %}

{% block content %}
<h1>Cart</h1>
<div class="m-2 col-8 m-auto">
    {% if cart_list == 'empty' %}
    <h1 class="alert alert-danger text-center">Your cart is empty! <br><span class="text-muted h5">Or maybe Bubbles stealed it from you :&lt; </span></h1>
    {% else %}
    <table class="table border-bottom table-hover">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Price</th>
            <th scope="col">Quality</th>
            <th scope="col">Options</th>
          </tr>
        </thead>
        <tbody>
        {% for product in cart_list %}
          <tr>
            <th scope="row">{{ product.cart_product.product_name }}</th>
            <td>{{ product.cart_product.product_price }} zł</td>
            <td><div class="input-group-sm">
              <input type="number" class="form-control" style="width: 75px" name="cartquantity" id="cartquantity-{{ product.id }}" value="{{ product.cart_quantity}}" onchange="updateCart('{% url 'mainsite:cart-update' product.id %}', {{ product.id }})" min="1" max="{{ product.cart_product.product_stock }}">
            </div></td>
            <td><a class="btn btn-danger btn-sm" href="{% url 'mainsite:cart-del' product.id %}">DELETE</a></td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
      <div>
        <div class="col-2 float-right">
          <button class="btn btn-primary mt-1 float-right" id="placeorder" onclick="order()">Place order</button>
        </div>
      </div>
    {% endif %}
</div>
{% endblock %}

{% block script-bottom %}
<script>
function updateCart(url, self)
{ 
  a = document.getElementById('cartquantity-'+self)
  b = parseInt(a.max);
  if (a.value <= 0 || a.value > b)
  {
    a.classList.add('border-danger')
    return
  }
  else
  {
    a.classList.remove('border-danger')
  }

  token = document.getElementsByName('csrfmiddlewaretoken')[0]
  console.log(a.value)
  let data = {cart_quantity: a.value}
  fetch(url, {
    method: 'POST',
    headers: {
    'Content-Type': 'application/json',
    'X-CSRFToken': token.value,
    },
    body: JSON.stringify(data)
  }).then(res => {
    console.log('Request sent '+token.value)
    console.log('Status code: ' + res.status)
  })
}
function order() {
  a = document.getElementById('placeorder');
  token = document.getElementsByName('csrfmiddlewaretoken')[0];
    fetch("{% url 'mainsite:customer-orders' %}", {
      method: 'POST',
      headers: {
        'X-CSRFToken': token.value
      }
    }).then(res => {
      if (res.status == 200)
      {
        window.location.reload(true);
      }
    });
}
</script>
{% endblock %}

mainsite/templates/mainsite/category.html
{% extends 'mainsite/base_template.html' %}
{% block title %}Category{% endblock %}
{% block content %}
<h1>{{ current_category.name }}</h1>
    <div class="col-md">
        {% if product_list %}
            {% load static %}
            <div class="row">
                {% for product in product_list %}
                <div class="card shadow-sm float-left mr-sm-3 mt-sm-2" style="width: 18rem;">
                    <img src="{% static 'mainsite/' %}{{ product.product_image }}" class="card-img-top" style="height: 150px;" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">{{ product.product_name }}</h5>
                        <h6 class="card-subtitle mb-2 text-muted">{{ product.product_price }} zł</h6>
                        <p class="card-text" style="height: 48px;">{{ product.product_description }}</p>
                        <a href="{% url 'mainsite:product' product.id %}" class="btn btn-primary stretched-link">View product</a>
                    </div>
                </div>
                {% endfor %}
            </div>
        {% else %}
        <h1 class="alert alert-danger text-center">There is no products in this category! <br><span class="text-muted h5"> :&lt; </span></h1>
        {% endif %}
    </div>
{% endblock %}

mainsite/templates/mainsite/customer-settings.html
{% extends 'mainsite/base_template.html' %}
{% block title %}Account Settings{% endblock %}

{% block content %}
<h1>Account Settings</h1>
<div class="row m-auto px-5 pt-3">
    <div class="col-2">
        <div class="list-group">
                <a href="" class="list-group-item list-group-item-action active">Account settings</a>
                <a href="{% url 'mainsite:customer-setting' 'address' %}" class="list-group-item list-group-item-action">Address</a>
        </div>
    </div>
    <div class="col-10">
        <div class="col-8 m-auto">
            {% if action == 'updateAccountInfo_success' %}
            <div class="alert alert-success">
                Your account details has been updated!
            </div>
            {% elif action == 'updateAccountInfo_error' %}
            <div class="alert alert-danger">
                Error occur when tried to update your account details, please check if you typed everything right!
            </div>
            {% endif %}
            <form action="" method="POST">
                {% csrf_token %}
                <div class="row">
                    <div class="col-6 form-group">
                        <label for="firstName">First Name:</label>
                        <input type="text" name="firstName" id="firstName" class="form-control" value="{{ req_user.first_name }}">
                    </div>
                    <div class="col-6 form-group">
                        <label for="lastName">Last Name:</label>
                        <input type="text" name="lastName" id="lastName" class="form-control" value="{{ req_user.last_name }}">
                    </div>
                </div>
                <div class="form-group">
                    <label for="email">e-mail:</label>
                    <input type="email" name="email" id="email" class="form-control" value="{{ req_user.email }}">
                </div>
                <div class="d-flex w-100 justify-content-end">
                    <button class="btn btn-danger" type="submit" name="action" value="updateAccountInfo">Update account information</button>
                </div>
            </form>
            {% if action == 'changePassword_success' %}
            <div class="alert alert-success">
                Your password has been updated!
            </div>
            {% elif action == 'changePassword_error' %}
            <div class="alert alert-danger">
                Error! Type again your current password and new password.
            </div>
            {% endif %}
            <form action="" method="POST" class="needs-validation" novalidate>
                {% csrf_token %}
                <div class="mb-2">
                    <div class="form-group">
                        <label for="oldPassword">Old password:</label>
                        <input type="password" name="oldPassword" id="oldPassword" class="form-control" required>
                        <div class="invalid-feedback">
                            Inapropriate password format!
                        </div>
                        <div class="valid-feedback">
                            Dobrze
                        </div>
                    </div>
                    <label for="newPassword">New password:</label>
                    <input type="password" name="newPassword" id="newPassword" class="form-control" required>
                    <div class="valid-feedback">
                        Dobrze
                    </div>
                    <label for="confirmNewPassword">New password confirmation:</label>
                    <input type="password" name="confirmNewPassword" id="confirmNewPassword" class="form-control" required>
                </div>
                <div class="d-flex w-100 justify-content-end">
                    <button class="btn btn-danger" type="submit" name="action" value="changePassword">Change my password</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block script-bottom %}
<script>
    window.onload = function() {
        // Fetch all the forms we want to apply custom Bootstrap validation styles to
        var forms = document.getElementsByClassName('needs-validation');
        // Loop over them and prevent submission
        var validation = Array.prototype.filter.call(forms, function(form) {
        form.addEventListener('submit', function(event) {
            console.log('TEST');
            if (form.checkValidity() === false) {
            event.preventDefault();
            event.stopPropagation();
            }
            form.classList.add('was-validated');
        }, false);
        });
    }

</script>
{% endblock %}

mainsite/templates/mainsite/order-complete.html
{% extends 'mainsite/base_template.html' %}
{% block title %}Order{% endblock %}

{% block content %}
<h1>Make order</h1>
<div class="col-6 m-auto">
    <div class="">
        <p class="alert alert-success">Order is complete</p>
    </div>
</div>
{% endblock %}

mainsite/templates/mainsite/product.html
{% extends 'mainsite/base_template.html' %}
{% block title %}Product{% endblock %}

{% block content %}
                <div class="col-9 mx-auto">
                    {% if product %}
                        {% load static %}
                        <div class="card shadow-sm text-light bg-dark">
                            
                            <div class="row float-left">
                                <div class="col-xl-8">
                                    <img src="{% static 'mainsite/' %}{{ product.product_image }}" class="img-fluid" alt="...">
                                </div>
                                <div class="col-xl-4">
                                    <div class="card-body">
                                        <div class="row">
                                            <div class="col-xl-8">
                                                <h5 class="card-title">{{ product.product_name }}</h5>
                                                <h6 class="card-subtitle mb-2 text-muted">{{ product.product_price }} zł</h6>
                                            </div>
                                            <div class="col-xl-4">
                                                <a href="{% url 'mainsite:cart-add' product.id %}" class="btn btn-primary float-right">Add to cart</a>                                        
                                            </div>
                                        </div>
                                            <div class="row">
                                                <div class="col-xl-12">
                                                    <h4 class="float-right">Product has been bought <span class="badge badge-info">{{ product.product_buy }} time{{product.product_buy|pluralize}}</span> </h4>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-xl-12">
                                                    <h5 class="float-right">Products in stock: <span class="badge {{ stock_color|default:'badge-secondary' }}">{{ product.product_stock }}</span></h5>
                                                </div>
                                            </div>
                                            <br>
                                        {% autoescape off %}
                                        <p class="card-text">{{ product.product_description }}</p>
                                        {% endautoescape %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% else %}
                    <div class="alert alert-danger" role="alert">
                        There is no products that are in this category!
                    </div>
                    {% endif %}
                </div>
{% endblock %}